DROP TABLE "CARDS" CASCADE CONSTRAINTS;
DROP TABLE "CUSTOMER" CASCADE CONSTRAINTS;
DROP TABLE "GASTYPE" CASCADE CONSTRAINTS;
DROP TABLE "RENT" CASCADE CONSTRAINTS;
DROP TABLE "RESERVATIONS" CASCADE CONSTRAINTS;
DROP TABLE "RETURN" CASCADE CONSTRAINTS;
DROP TABLE "STATUS" CASCADE CONSTRAINTS;
DROP TABLE "VEHICLE" CASCADE CONSTRAINTS;
DROP TABLE "VEHICLETYPES" CASCADE CONSTRAINTS;

