DROP TABLE "STATUS" CASCADE CONSTRAINTS;
DROP TABLE "AUTHORS" CASCADE CONSTRAINTS;
DROP TABLE "PUBLISHERS" CASCADE CONSTRAINTS;
DROP TABLE "TITLES" CASCADE CONSTRAINTS;
DROP TABLE "TITLEAUTHORS" CASCADE CONSTRAINTS;
DROP TABLE "EDITORS" CASCADE CONSTRAINTS;
DROP TABLE "TITLEDITORS" CASCADE CONSTRAINTS;
DROP TABLE "SALES" CASCADE CONSTRAINTS;
DROP TABLE "SALESDETAILS" CASCADE CONSTRAINTS;
DROP TABLE "HELLO" CASCADE CONSTRAINTS;
DROP TABLE "CUSTOMER" CASCADE CONSTRAINTS;
DROP TABLE "RENT" CASCADE CONSTRAINTS;
DROP TABLE "RETURNS" CASCADE CONSTRAINTS;
DROP TABLE "VEHICLETYPES" CASCADE CONSTRAINTS;

